# Generated by Django 5.2.5 on 2025-08-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_book_travel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Travel',
        ),
        migrations.AlterField(
            model_name='book',
            name='Author_name',
            field=models.CharField(max_length=60),
        ),
    ]
